### ISSUE TITLE
Option to use babel.js rather than traceur

### ISSUE THREAD

**Issue by asaf-romano** [fitzgen/wu.js#23]
When using wu.js in a node.js environment, it seems it requires traceurRuntime to be available in the global scope (the documentation only mentions it as required in the browser environment, by the way). For a babel.js (which has no runtime) based project, it doesn't make sense to have traceurRuntime available in the global scope.

Using babel's "require hook" I tried to work around this by importing wu.js (rather than we.es5.js). This didn't get me too far unfortunately: I think because wu.js depends on particular aspects of traceur wrt. Symbols, but I'll have to check this again as I lost the error message. Please let me know if that's necessary.

**Comment by fitzgen** [comment]
Ah, this is because at one point in time I was including the tracuer-runtime inside `wu.es5.js`, but forgot to update the docs. Easiest fix is probably to modify the `compile-to-es5.sh` script to also output `wu.node.js` which is the traceur-runtime + `wu.es5.js`.

Would also be open to using babel. Don't have strong opinions. Perhaps wu.js should only be the ES6 version and let users compile to ES5 however they choose.

**Comment by asaf-romano** [comment]
Thanks for the reply!

Would you like me to separate the wu.node.js issue to its own ticket?

Yes, ideally wu.js wouldn't know anything about the transpiler it is compiled with. Importing wu.js with the babel "require hook" (there is a similar tool for tracuer, IIRC) would just work.

**Comment by gso** [comment]
Does wu.js require any non standard ES 2015 features, will a transpiler still be needed after June?

Wu is a require of EonJS https://bitbucket.org/gso/eonjs/src btw (much appreciated, has saved a fair few lines of code).

**Comment by fitzgen** [comment]
It doesn't use any non-standard features, but whether you need to use a transpiler depends on your target environment's ES2015 implementation level.

**Comment by johnnyreilly** [comment]
Is there any news on this? I can see there's an fork....

https://www.npmjs.com/package/wu-babel

**Comment by fitzgen** [comment]
Switched to babel in 2c287fffb3c39af71169c3103361988e7121c068.

**Comment by johnnyreilly** [comment]
Sweet!
