### ISSUE TITLE
Docs to be updated?

### ISSUE THREAD

**Issue by johnnyreilly** [fitzgen/wu.js#27]
Hi @fitzgen,

First of all, great work on wu js - I'm planning to switch to it to get back that chaining goodness when dealing with iterables.

I can see you've just switched from Traceur to Babel (yay!) but I notice the docs still all reference Traceur etc. Are you planning to update these?

Thanks again,
John

**Comment by fitzgen** [comment]
Just forgot to update the gh-pages branch. Should be fixed in the next few minutes.

**Comment by johnnyreilly** [comment]
Thanks chap - I hope to give this a whirl on Monday
