### ISSUE TITLE
pluck() not curryable ?

### ISSUE THREAD

**Issue by olivr70** [fitzgen/wu.js#29]
hello,

I am just starting experimenting with wu, so may be I got it wrong, but the following code fails on node 4.2.0.

The code is just a rewrite of one the unit test, fails

```
  var wu = require("wu");

  var pluck_i = wu.pluck("i");
  var arr = pluck_i([{ i: 1 }, { i: 2 }, { i: 3 }]);  // throws pluck_i() is not a function
  console.log(arr);  // should display [1,2,3]
```

Did I get anything wrong ?

**Comment by honzabrecka** [comment]
Fixed in #50
