### ISSUE TITLE
Add toArray method ?

### ISSUE THREAD

**Issue by FredyC** [fitzgen/wu.js#35]
I am curious why something that essential (in my opinion) is missing here. I mean it's nice and pretty to have these transformations and stuff, but sometimes converting to good old array might be useful too. For example I was writing unit test where I wanted to verify that iterator returned all expected items. I had to do awkward thing like this:

``` js
const actual = [];
for (const item of iterator) {
    actual.push(item);
}
expect(actual).to.be.eql(expected);
```

Might be simple to write just `expect(wu(iterator).toArray()).to.be.eql(expected)`.

I am sure there could be more use cases. I know I could create such wrapping function by myself quiet easily, but might be handy to have that in wu also, don't you agree? Are there perhaps some other libraries that could fill the gap?

**Comment by rauschma** [comment]
Not necessary. There are two fairly compact ways of converting an iterable to an Array in ES6:

```js
let arr1 = [...iterable1];
let arr2 = Array.from(iterable2);
```

**Comment by FredyC** [comment]
Ah I see, I didn't knew it's possible like this. Maybe it might be worth to be mentioned in docs here for other clueless people like me :) I could do a PR if there is a agreement on that.

**Comment by fitzgen** [comment]
I would merge such a PR.

**Comment by chocolateboy** [comment]
In case anyone is still waiting for this, while it's not documented, it's [available](https://github.com/fitzgen/wu.js/blob/182855be57b7c69695836c0fae7860064af441e0/wu.js#L480-L482), and has been [since 2014](https://github.com/fitzgen/wu.js/commit/7bb63d89e15af1def9f0f86f5a421a038ef0fdb3).

**Comment by DanielSWolf** [comment]
For the record: I'm glad this feature exists, and I believe it's very useful (and should be documented).

Here's why: The full power of wu.js (like LINQ) comes from chaining calls. And I find that having to wrap a multi-line expression makes it much harder to read. Compare:

```js
const lookingGood = bar
  .map(...)
  .filter(...)
  .zip(...)
  .toArray();

const lookingBad1 = [...bar
  .map(...)
  .filter(...)
  .zip(...)];

const lookingBad2 = Array.from(bar
  .map(...)
  .filter(...)
  .zip(...));
```
