### ISSUE TITLE
chain() non-iterables

### ISSUE THREAD

**Issue by msklvsk** [fitzgen/wu.js#42]
I often need to create an iterable of "this and children" or "this and this.nextSiblings()", which I do with `wu.chain([this], this.children())`. How about making `.chain()` accept non-iterables, like this:
```js
rewrapStaticMethod("chain", function* (...iteratees) {
  for (let it of iteratees) {
    if (isIterable(it)) {
      yield* it;
    } else {
      yield it;
    }
  }
});
```
so it is possible to write `wu.chain(this, that, someIterable(), tailBonus)`.

**Comment by fitzgen** [comment]
Generally, I'm not in favor of these kinds of APIs that accept all the possible things you could throw at them with all these different types, and just trying to do the Right Thing. Behavior becomes hard to predict and trying to handle all the edge cases that might make sense in isolation leads towards insanity in aggregate.

If you really want this, feel free to make your own module that adds a `chainAllTheThings` method to wu or something like that.
