### ISSUE TITLE
API section of docs is empty?

### ISSUE THREAD

**Issue by vith** [fitzgen/wu.js#47]
![screenshot from 2017-07-24 17-59-36](https://user-images.githubusercontent.com/3265539/28548503-ee7e9992-7099-11e7-8728-81f4c271e3ed.png)

**Comment by mlaflamm** [comment]
+1. Please fix the documentation which is not online anymore.

**Comment by tobia** [comment]
In the meantime, Archive.org has us covered:

https://web.archive.org/web/20170613142422/https://fitzgen.github.io/wu.js/

**Comment by loyd** [comment]
@fitzgen, please, pay attention!

**Comment by CrossEye** [comment]
@loyd: Notice #48.  Are you interested?
