### ISSUE TITLE
npm package is outdated

### ISSUE THREAD

**Issue by levabala** [fitzgen/wu.js#58]
Please, can u update the npm package of "wu"?
I've started using it and discovered that there are no "nth" function that was [mentioned](https://fitzgen.github.io/wu.js/#nth) at docs

**Comment by levabala** [comment]
As well as @types/wu

**Comment by vitaly-t** [comment]
This doesn't look supported anymore. Here's a fresh take on this: [iter-ops](https://github.com/vitaly-t/iter-ops).
